// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJkZZpaGCXOFnxSMxp1frl3YSVOGnnJCI',
    appId: '1:246203678852:web:6979db773feaecbdbf82d1',
    messagingSenderId: '246203678852',
    projectId: 'fir-demo-d5c9b',
    authDomain: 'fir-demo-d5c9b.firebaseapp.com',
    storageBucket: 'fir-demo-d5c9b.firebasestorage.app',
    measurementId: 'G-MNVM8TESLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fX3w2P13qdz8QtguzGO8BpsofXGamCk',
    appId: '1:246203678852:android:1d67dc75e6002cd2bf82d1',
    messagingSenderId: '246203678852',
    projectId: 'fir-demo-d5c9b',
    storageBucket: 'fir-demo-d5c9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLkn19Yfo90EU3KTERdnvJ8625vtyisYA',
    appId: '1:246203678852:ios:d2a34a16feb5d77cbf82d1',
    messagingSenderId: '246203678852',
    projectId: 'fir-demo-d5c9b',
    storageBucket: 'fir-demo-d5c9b.firebasestorage.app',
    iosBundleId: 'com.example.padhai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLkn19Yfo90EU3KTERdnvJ8625vtyisYA',
    appId: '1:246203678852:ios:d2a34a16feb5d77cbf82d1',
    messagingSenderId: '246203678852',
    projectId: 'fir-demo-d5c9b',
    storageBucket: 'fir-demo-d5c9b.firebasestorage.app',
    iosBundleId: 'com.example.padhai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJkZZpaGCXOFnxSMxp1frl3YSVOGnnJCI',
    appId: '1:246203678852:web:ee6e79ff6908a397bf82d1',
    messagingSenderId: '246203678852',
    projectId: 'fir-demo-d5c9b',
    authDomain: 'fir-demo-d5c9b.firebaseapp.com',
    storageBucket: 'fir-demo-d5c9b.firebasestorage.app',
    measurementId: 'G-RBYP5LPGDG',
  );
}
